//This file was generated by Map Builder
//To load this objects copy this script to your mission and put
// nil = [] execVM "cop_vladimir.sqf";
//in your init.sqf or a trigger-activation.
private["_obj"];
_obj = "Land_dar_ilpda3" createvehicle [1383.869995,17527.800781,-0.0420874];
_obj setposATL [1383.869995,17527.800781,-0.0420874];
_obj setVectorDirAndUp [[0.156609,0.987661,0],[0,0,1]];
_obj setposATL [1383.869995,17527.800781,-0.0420874];
_obj = "Orel_Borne_Escamotable" createvehicle [1389.849976,17515.699219,-0.0336695];
_obj setposATL [1389.849976,17515.699219,-0.0336695];
_obj setVectorDirAndUp [[0.147112,0.98912,0],[0,0,1]];
_obj setposATL [1389.849976,17515.699219,-0.0336695];
_obj = "Orel_Iron_Barrier" createvehicle [1374.25,17513.5,0];
_obj setposATL [1374.25,17513.5,0];
_obj setVectorDirAndUp [[0.156434,0.987688,0],[0,0,1]];
_obj setposATL [1374.25,17513.5,0];
_obj = "Orel_Iron_Barrier" createvehicle [1377.0245361,17513.0683594,0];
_obj setposATL [1377.0245361,17513.0683594,0];
_obj setVectorDirAndUp [[0.156434,0.987688,0],[0,0,1]];
_obj setposATL [1377.0245361,17513.0683594,0];
_obj = "Orel_Iron_Barrier" createvehicle [1379.835205,17512.601563,0];
_obj setposATL [1379.835205,17512.601563,0];
_obj setVectorDirAndUp [[0.156434,0.987688,0],[0,0,1]];
_obj setposATL [1379.835205,17512.601563,0];
_obj = "Orel_Iron_Barrier" createvehicle [1382.630615,17512.142578,0];
_obj setposATL [1382.630615,17512.142578,0];
_obj setVectorDirAndUp [[0.156434,0.987688,0],[0,0,1]];
_obj setposATL [1382.630615,17512.142578,0];
_obj = "Orel_Iron_Barrier" createvehicle [1385.386841,17511.714844,0];
_obj setposATL [1385.386841,17511.714844,0];
_obj setVectorDirAndUp [[0.156434,0.987688,0],[0,0,1]];
_obj setposATL [1385.386841,17511.714844,0];
