//This file was generated by Map Builder
//To load this objects copy this script to your mission and put
// nil = [] execVM "cop_sabina.sqf";
//in your init.sqf or a trigger-activation.
private["_obj"];
_obj = "Land_dar_ilpda3" createvehicle [15432.0996094,10054.900391,0];
_obj setposATL [15432.0996094,10054.900391,0];
_obj setVectorDirAndUp [[1,-4.37114e-008,0],[0,-0,1]];
_obj setposATL [15432.0996094,10054.900391,0];
_obj = "Land_Benzina" createvehicle [15484.299805,10056.299805,-9.53674e-007];
_obj setposATL [15484.299805,10056.299805,-9.53674e-007];
_obj setVectorDirAndUp [[-0.0251127,-0.999685,0],[-0,0,1]];
_obj setposATL [15484.299805,10056.299805,-9.53674e-007];
_obj = "Orel_Borne_Escamotable" createvehicle [15415.015625,10065.0507813,0];
_obj setposATL [15415.015625,10065.0507813,0];
_obj setVectorDirAndUp [[0,1,0],[0,0,1]];
_obj setposATL [15415.015625,10065.0507813,0];
