//This file was generated by Map Builder
//To load this objects copy this script to your mission and put
// nil = [] execVM "cop_krasno.sqf";
//in your init.sqf or a trigger-activation.
private["_obj"];
_obj = "Land_dar_ilpdn" createvehicle [9358.401367,7668.894043,-0.00841677];
_obj setposATL [9358.401367,7668.894043,-0.00841677];
_obj setVectorDirAndUp [[0.788011,-0.615662,0],[0,-0,1]];
_obj setposATL [9358.401367,7668.894043,-0.00841677];
_obj = "Orel_Borne_Escamotable" createvehicle [9348.0595703,7681.490234,0];
_obj setposATL [9348.0595703,7681.490234,0];
_obj setVectorDirAndUp [[-0.778637,0.627474,0],[0,0,1]];
_obj setposATL [9348.0595703,7681.490234,0];
_obj = "Orel_Borne_Escamotable" createvehicle [9329.94043,7658.319824,0];
_obj setposATL [9329.94043,7658.319824,0];
_obj setVectorDirAndUp [[-0.784137,0.620587,0],[0,0,1]];
_obj setposATL [9329.94043,7658.319824,0];
