//This file was generated by Map Builder
//To load this objects copy this script to your mission and put
// nil = [] execVM "cop_lyepestok.sqf";
//in your init.sqf or a trigger-activation.
private["_obj"];
_obj = "Land_dar_ilpda3" createvehicle [11485.299805,15661.400391,0];
_obj setposATL [11485.299805,15661.400391,0];
_obj setVectorDirAndUp [[0.0101399,-0.999949,0],[0,-0,1]];
_obj setposATL [11485.299805,15661.400391,0];
_obj = "Orel_Iron_Barrier" createvehicle [11480.900391,15681.200195,0];
_obj setposATL [11480.900391,15681.200195,0];
_obj setVectorDirAndUp [[0.00881495,0.999961,0],[0,0,1]];
_obj setposATL [11480.900391,15681.200195,0];
_obj = "Orel_Iron_Barrier" createvehicle [11471.400391,15680.900391,0];
_obj setposATL [11471.400391,15680.900391,0];
_obj setVectorDirAndUp [[-0.0220417,0.999757,0],[0,0,1]];
_obj setposATL [11471.400391,15680.900391,0];
_obj = "Orel_Iron_Barrier" createvehicle [11472.799805,15682.299805,0];
_obj setposATL [11472.799805,15682.299805,0];
_obj setVectorDirAndUp [[-0.999391,0.0348998,0],[0,0,1]];
_obj setposATL [11472.799805,15682.299805,0];
_obj = "Orel_Iron_Barrier" createvehicle [11479.5,15682.599609,0];
_obj setposATL [11479.5,15682.599609,0];
_obj setVectorDirAndUp [[0.999981,0.0061715,0],[0,0,1]];
_obj setposATL [11479.5,15682.599609,0];
_obj = "Orel_Iron_Barrier" createvehicle [11469.900391,15679.5,0];
_obj setposATL [11469.900391,15679.5,0];
_obj setVectorDirAndUp [[-0.999394,0.0348126,0],[0,0,1]];
_obj setposATL [11469.900391,15679.5,0];
_obj = "Orel_Iron_Barrier" createvehicle [11482.299805,15679.700195,0];
_obj setposATL [11482.299805,15679.700195,0];
_obj setVectorDirAndUp [[0.999662,0.0260006,0],[0,0,1]];
_obj setposATL [11482.299805,15679.700195,0];
_obj = "Orel_Borne_Escamotable" createvehicle [11477.400391,15672.799805,0.0336701];
_obj setposATL [11477.400391,15672.799805,0.0336701];
_obj setVectorDirAndUp [[0,1,0],[0,0,1]];
_obj setposATL [11477.400391,15672.799805,0.0336701];
